import { useState } from 'react';
import { ArrowDownToLine, ArrowUpRight, CalendarDays, CircleHelp, FileText, LocateFixed, MapPin, Printer, Route, X } from 'lucide-react';
import { TIERS, UTILITY_NAMES, type Opportunity, type Project } from '../../../shared/types';
import { center } from '../../../shared/analysis';
import { formatDate } from './Timeline';
export default function Details({ pair, projects, inspected, onClose, onZoom, onExport, onPrint }: {
  pair: Opportunity | null; projects: Project[]; inspected: Project | null;
  onClose(): void; onZoom(id: string): void; onExport(): void; onPrint(): void;
}) {
  const [tab, setTab] = useState<'overview' | 'evidence'>('overview');
  const shown = pair ? projects.filter(p => p.id === pair.projectA || p.id === pair.projectB) : inspected ? [inspected] : [];
  if (!shown.length) return <aside className="details-panel no-selection"><div className="panel-heading"><span className="eyebrow">OPPORTUNITY DETAILS</span><CircleHelp size={16}/></div><div className="selection-intro"><div className="selection-graphic"><MapPin size={24}/><span/><MapPin size={24}/></div><h2>A closer look at<br/>what’s nearby.</h2><p>Select an opportunity to explore its location, timing, and potential for coordination.</p></div><div className="tier-guide"><span className="eyebrow">THREE WAYS TO COORDINATE</span>{TIERS.map(t => <div className="tier-guide-row" key={t.id}><span className={`tier-number tier-${t.id}`}>{t.id}</span><div><strong>{t.name} proximity</strong><p>{t.scenario}</p></div><span>{t.range}</span></div>)}</div><div className="method-note"><FileText size={17}/><div><strong>Evidence comes first</strong><p>These are geographic candidates. Shared schedules, routes, and resources need further verification.</p></div></div></aside>;
  const tier = pair ? TIERS[pair.tier - 1] : null;
  return <aside className="details-panel has-selection"><div className="panel-heading"><span className="eyebrow">{pair ? 'SELECTED OPPORTUNITY' : 'PROJECT DETAILS'}</span><button className="icon-button" aria-label="Close details" onClick={onClose}><X size={17}/></button></div><div className="detail-title">{tier && <span className={`tier-badge tier-${tier.id}`}>Tier {tier.id} · {tier.name}</span>}<h2>{pair ? tier!.scenario : inspected!.shortName}</h2><p>{pair ? 'Cross-utility coordination candidate' : 'No geographic match in the current results'}</p></div>
    {pair && <div className="detail-metrics"><div><span><Route size={14}/> CENTER DISTANCE</span><strong>{pair.distanceMi.toFixed(2)} <small>mi</small></strong></div><div><span><CalendarDays size={14}/> DATE GAP</span><strong>{pair.timeGapDays?.toLocaleString() ?? '—'} <small>days</small></strong></div></div>}
    <div className="detail-tabs" role="tablist" aria-label="Opportunity details">{(['overview', 'evidence'] as const).map(t => <button key={t} id={`tab-${t}`} role="tab" aria-controls={`detail-${t}`} aria-selected={tab === t} onClick={() => setTab(t)}>{t === 'overview' ? 'Overview' : 'Evidence'}{t === 'evidence' && <FileText size={14}/>}</button>)}</div>
    <div className="detail-content" role="tabpanel" id={`detail-${tab}`} aria-labelledby={`tab-${tab}`}>
      {tab === 'overview' ? <>{shown.map(p => <section className="project-detail" key={p.id}><div className="utility-label"><i className={`utility-dot ${p.utility.toLowerCase()}`}/>{UTILITY_NAMES[p.utility]}<span>{p.id}</span></div><h3>{p.shortName}</h3><p className="full-project-name">{p.name}</p><div className="project-facts"><span>Planned in-service</span><strong>{formatDate(p.inServiceDate)}</strong><span>Located endpoints</span><strong>{p.endpoints.filter(e => e.coordinates).length} of 2</strong></div><button className="text-button" onClick={() => onZoom(p.id)}><LocateFixed size={15}/> Inspect at street level<ArrowUpRight size={13}/></button></section>)}{pair && <section className="coordination-note"><span className="eyebrow">POTENTIAL TO EXPLORE</span><p>{tier!.description}</p><span>Proximity does not establish shared land or overlapping construction.</span></section>}</> : <>{shown.map(p => <section className="evidence-section" key={p.id}><div className="utility-label"><i className={`utility-dot ${p.utility.toLowerCase()}`}/>{p.id}</div><h3>{p.shortName}</h3><dl><dt>Primary source</dt><dd>Projects_Overlaps.xlsx<br/>projects · row {p.sourceRow}</dd><dt>Center method</dt><dd>{p.endpoints.filter(e => e.coordinates).length === 2 ? 'Arithmetic midpoint of two endpoints' : 'Single located endpoint'}</dd><dt>Center coordinates</dt><dd>{center(p)?.map(v => v.toFixed(6)).join(', ')}<small>Longitude, latitude</small></dd><dt>Original date value</dt><dd>{p.rawDate} · workbook in-service date</dd>{p.document && <><dt>Supporting document</dt><dd>{p.document}<br/>PDF page {p.documentPage} · ID {p.sourceProjectId}</dd></>}</dl><ul className="evidence-notes">{p.notes.map(note => <li key={note}>{note}</li>)}</ul></section>)}</>}
    </div>
    {pair && <div className="detail-actions"><button className="primary-button" onClick={onExport}><ArrowDownToLine size={16}/> Export pair summary</button><button className="secondary-button" onClick={onPrint}><Printer size={15}/> Print / Save PDF</button></div>}
  </aside>;
}
